name: Build, push and deploy Docker image

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '24 3 * * 1'

# Enables BuildKit
env:
  DOCKER_BUILDKIT: 1

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - node_version: '16'
          - node_version: '18'

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: thecodingmachine/workadventure-back-base:v1-${{ matrix.node_version }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            NODE_VERSION=${{ matrix.node_version }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
